sudo: false
dist: xenial
language: node_js
node_js:
    - "10"
    - "12"
env:
  - DB=postgres10
  - DB=postgres11   
cache:
  directories:
    - "node_modules"   
git:
  depth: 5
services:
  - docker
  
# jobs:
#   include:
#     - stage: pgsql10
#       sudo: require
#       service: 
#         - docker    
#       before_script:
#         - bash ./testing/travis/install-postgres-10.sh
#     - stage pgsql11
#       sudo: require
#       service: 
#         - docker    
#       before_script:

#         - bash ./testing/travis/install-postgres-11.s
before_install:
  - npm i -g npm@latest 

install:
  - npm intall
  - npm install -g codecov @zeit/ncc@beta
  
before_script:
  - sh -c "if [ '$DB' = 'postgres10' ]; then bash ./testing/travis/install-postgres-10.sh; echo $DB; fi"
  - sh -c "if [ '$DB' = 'postgres11' ]; then bash ./testing/travis/install-postgres-11.sh; echo $DB; fi"  

script:
  - npm run test.nest.upms.e2e
  - bash <(curl -s https://codecov.io/bash)
#   - rm -rf tsconfig.json && cp  ./apps/nest-upms/tsconfig.json ./
  - export NODE_OPTIONS=--max_old_space_size=4096 && cd ./apps/nest-upms && ncc build ./src/main.ts -o dist -m

#   - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
#   - codecov
 
after_success: cd ../../ && npm run test.nest.upms.coverage

notifications:
    webhooks: https://www.travisbuddy.com/
