# sudo: required
# dist: xenial
language: node_js
node_js:
    - "10"
    - "12"
cache:
  directories:
    - "node_modules"   
git:
  depth: 5
services:
  - postgresql
#  - postgresql
# addons:
#   postgresql: "11"
#   apt:
#     packages:
#     - postgresql-11
#     - postgresql-client-11
# env:
  # global:
    # - PGPORT=5432
    # - PGDATABASE=test
    # - PGUSER=postgres
    # - PGHOST=localhost
    # - DB=postgres
  
before_script:
#   - sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
#   - sudo service postgresql restart
#   - sleep 1
 # - psql -U postgres -c "create extension postgis"
  # - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'create database test_ci;' -U postgres; echo $DB; fi"
  # - export DISPLAY=:99.0
  - sh -c "psql -c 'create database test_ci;' -U postgres;"
  - npm i -g npm@latest
  - npm install -g codecov

install:
  - npm i
script:
  - npm run test.nest.upms.e2e
#   - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
#   - codecov
after_script:
  - bash <(curl -s https://codecov.io/bash)
after_success: npm run test.nest.upms.coverage
