version: '3'
services:
  # prisma:
  #   image: prismagraphql/prisma:1.32
  #   restart: always
  #   ports:
  #   - "4466:4466"
  #   environment:
  #     PRISMA_CONFIG: |
  #       port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        # databases:
        #   default:
        #     connector: postgres
        #     host: postgres
        #     user: prisma
        #     password: prisma
        #     rawAccess: true
        #     port: 5432
        #     migrations: true
  postgres:
    image: postgres:10-alpine
    restart: always
    # Uncomment the next two lines to connect to your your database from outside the Docker environment, e.g. using a database GUI like Postico
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_ci
    volumes:
      - ~/data/postgres:/var/lib/postgresql/data
volumes:
  postgres:
